# Generated by Django 2.2.14 on 2022-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220716_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(default='', max_length=50),
        ),
    ]
